version: '3.5'

services:
  rails_api:
    container_name: rails_api
    build: .
    image: rails_api
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
    ports:
      - 7770:7770
    env_file:
      - .env.local
  database:
    container_name: postgres_db
    image: postgres:9.6
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 7772:5432
    env_file:
      - .env.local
volumes:
  database:
